const INCH_TO_POINTS = 72;
const MM_TO_POINTS = INCH_TO_POINTS / 25.4;

const CROP_MARK_LENGTH_POINTS = 18;
const CROP_MARK_OFFSET_POINTS = 9;
const CROP_MARK_THICKNESS_POINTS = 0.5;

const QR_TARGET_SIZE_INCHES = 0.8;
const QR_CODE_SIZE_POINTS = QR_TARGET_SIZE_INCHES * INCH_TO_POINTS;
const QR_GENERATION_PIXEL_SIZE = 240;

const SLUG_AREA_MARGIN_POINTS = 9;
const SLUG_TEXT_FONT_SIZE_POINTS = 7;
const SLUG_TEXT_QR_PADDING_POINTS = 7;
const SLUG_AREA_BOTTOM_Y_POINTS = QR_CODE_SIZE_POINTS * 0.15;

const QR_SLUG_SHIFT_RIGHT_MM = 2;
const QR_SLUG_SHIFT_RIGHT_POINTS = QR_SLUG_SHIFT_RIGHT_MM * MM_TO_POINTS;

module.exports = {
    INCH_TO_POINTS,
    MM_TO_POINTS,
    CROP_MARK_LENGTH_POINTS,
    CROP_MARK_OFFSET_POINTS,
    CROP_MARK_THICKNESS_POINTS,
    QR_CODE_SIZE_POINTS,
    QR_GENERATION_PIXEL_SIZE,
    SLUG_AREA_MARGIN_POINTS,
    SLUG_TEXT_FONT_SIZE_POINTS,
    SLUG_TEXT_QR_PADDING_POINTS,
    SLUG_AREA_BOTTOM_Y_POINTS,
    QR_SLUG_SHIFT_RIGHT_POINTS
};
